### ISSUE TITLE
Failed to resolve: com.stefanosiano.powerfullibraries:imageview:0.3.13

### ISSUE THREAD

**Issue by Roxin92** [stefanosiano/PowerfulImageView#2]
Failed to resolve: com.stefanosiano.powerfullibraries:imageview:0.3.13

**Comment by stefanosiano** [comment]
Forgot to update the readme, sorry.
New gradle instructions:
    implementation 'com.stefanosiano.powerful_libraries:imageview:1.0.10'
    implementation 'com.stefanosiano.powerful_libraries:imageview_databinding:1.0.1' //To have support for Android data binding
